//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClientApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IOldWcfService")]
    public interface IOldWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOldWcfService/GetAllProducts", ReplyAction="http://tempuri.org/IOldWcfService/GetAllProductsResponse")]
        System.Data.DataSet GetAllProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOldWcfService/GetAllProducts", ReplyAction="http://tempuri.org/IOldWcfService/GetAllProductsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllProductsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOldWcfServiceChannel : WcfClientApp.ServiceReference1.IOldWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OldWcfServiceClient : System.ServiceModel.ClientBase<WcfClientApp.ServiceReference1.IOldWcfService>, WcfClientApp.ServiceReference1.IOldWcfService {
        
        public OldWcfServiceClient() {
        }
        
        public OldWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OldWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OldWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OldWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllProducts() {
            return base.Channel.GetAllProducts();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllProductsAsync() {
            return base.Channel.GetAllProductsAsync();
        }
    }
}
